index:
  slogan:
    enable: true
    text: Stay Hungry, Stay Foolish.

navbar:
  blog_title: QPing's Blog

post:
  comments:
    enable: true
    type: utterances

utterances:
  repo: 'qpingcode/qpingcode.github.io'
  issue_term: 'pathname'