favicon: /images/favicon3.svg

index:
  slogan:
    enable: true
    text: Stay Hungry, Stay Foolish.

navbar:
  blog_title: QPing's Blog
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "mytools", name: "MyTools 手册", link: "/mytools/" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

post:
  comments:
    enable: true
    type: utterances

utterances:
  repo: 'qpingcode/qpingcode.github.io'
  issue_term: 'pathname'
