index:
  slogan:
    enable: true
    text: Stay Hungry, Stay Foolish.

post:
  comments:
    enable: true
    type: utterances

utterances:
  repo: 'qpingcode/qpingcode.github.io'
  issue_term: 'pathname'